language: bash
matrix:
  include:
    - os: linux
      script: make travis
    - os: osx
      script: make travis
    - os: windows
      install: choco install mingw
      script: mingw32-make travis

      
      
      