language: bash
matrix:
  include:
    - os: linux
      script: make travis
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gcc-4.9
      env:
         - COMPILER="CC=gcc-4.9 && CXX=g++-4.9"
      before_install: eval "${COMPILER}"
      script: make travis
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env:
         - COMPILER="CC=gcc-5 && CXX=g++-5"
      before_install: eval "${COMPILER}"
      script: make travis
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
         - COMPILER="CC=gcc-7 && CXX=g++-7"
      before_install: eval "${COMPILER}"
      script: make travis
    - os: linux
      compiler: clang
      script: make travis
    - os: osx
      script: make travis
    - os: osx
      osx_image: xcode10
      script: make travis
    - os: windows
      install: choco install mingw
      script: mingw32-make travis
    - os: windows
      install: choco install mingw --version 4.9.3 --force
      script: mingw32-make travis
    - os: windows
      env:
        - CMAKE_PATH="/c/Program Files/CMake/bin"
      script: 
        - export PATH=$CMAKE_PATH:$PATH
        - mkdir build && cd build
        - cmake .. 
        - cmake --build . 



      
      
      